import type { BrandConfig } from '../index';

export const mobilidadBrand: BrandConfig = {
  id: 'mobilidad',
  appName: 'Mobilidad',
  tagline: 'Tu viaje, tus reglas',
  logoText: 'M',
  description: 'Plataforma de movilidad con tarifa negociable para conectar pasajeros y conductores.',
  colors: {
    primary: '#6C63FF',
    primaryForeground: '#FFFFFF',
    secondary: '#00D4AA',
    secondaryForeground: '#0A0A0F',
    accent: '#6C63FF',
    background: '#0A0A0F',
    surface: '#111118',
    foreground: '#FFFFFF',
    muted: '#1A1A24',
    mutedForeground: '#8B8B9E',
    border: 'rgba(255,255,255,0.08)',
    success: '#22C55E',
    warning: '#F59E0B',
    error: '#EF4444',
  },
  typography: {
    fontSans: 'Inter',
    fontMono: 'JetBrains Mono',
  },
  legal: {
    companyName: 'Mobilidad Technologies S.A. de C.V.',
    jurisdiction: 'México',
    contactEmail: 'legal@mobilidad.mx',
    taxId: 'MTC000101AAA',
  },
  features: {
    negotiableFares: true,
    scheduledRides: true,
    multiplePaymentMethods: true,
    driverRating: true,
    passengerRating: true,
    realTimeTracking: true,
    inAppChat: true,
    surgeMultiplier: true,
    corporateAccounts: false,
  },
  fares: {
    currency: 'MXN',
    currencySymbol: '$',
    locale: 'es-MX',
    baseFare: 30,
    perKmRate: 8,
    perMinRate: 1.5,
    maxSurgeMultiplier: 3.0,
    platformCommissionPercent: 18,
    minFare: 35,
    maxFare: 2000,
  },
  supportedLanguages: ['es', 'en'],
  defaultLanguage: 'es',
  mapsProvider: 'google',
  websiteUrl: 'https://mobilidad.mx',
};
