import type { BrandConfig } from '../index';

export const ridemeBrand: BrandConfig = {
  id: 'rideme',
  appName: 'RideMe',
  tagline: 'Your ride, your price',
  logoText: 'R',
  description: 'Ride-hailing platform with negotiable fares connecting passengers and drivers.',
  colors: {
    primary: '#6C63FF',
    primaryForeground: '#FFFFFF',
    secondary: '#00D4AA',
    secondaryForeground: '#0A0A0F',
    accent: '#FF4DC4',
    background: '#0A0A0F',
    surface: '#111118',
    foreground: '#FFFFFF',
    muted: '#1A1A24',
    mutedForeground: '#8B8B9E',
    border: 'rgba(255,255,255,0.08)',
    success: '#22C55E',
    warning: '#F59E0B',
    error: '#EF4444',
  },
  typography: {
    fontSans: 'Inter',
    fontMono: 'JetBrains Mono',
  },
  legal: {
    companyName: 'RideMe Inc.',
    jurisdiction: 'México',
    contactEmail: 'legal@rideme.app',
  },
  features: {
    negotiableFares: true,
    scheduledRides: true,
    multiplePaymentMethods: true,
    driverRating: true,
    passengerRating: true,
    realTimeTracking: true,
    inAppChat: true,
    surgeMultiplier: true,
    corporateAccounts: true,
  },
  fares: {
    currency: 'MXN',
    currencySymbol: '$',
    locale: 'es-MX',
    baseFare: 35,
    perKmRate: 9,
    perMinRate: 1.8,
    maxSurgeMultiplier: 2.5,
    platformCommissionPercent: 18,
    minFare: 40,
    maxFare: 2500,
  },
  supportedLanguages: ['es', 'en'],
  defaultLanguage: 'es',
  mapsProvider: 'google',
  websiteUrl: 'https://rideme.app',
};
